/* Generated by bench/report.py. Do not edit by hand.
 * Source: bench/results.json, measured on Apple M5 Pro.
 */
window.BLOOM_DATA = {
 "meta": {
  "machine": "Apple M5 Pro",
  "compiler": "21.0.0 (clang-2100.1.1.101)",
  "key_bytes": 16,
  "reps": 7,
  "l1d_bytes": 131072,
  "l2_bytes": 16777216,
  "cache_line_bytes": 128,
  "block_bits": 512
 },
 "fpr_vs_bits": [
  {
   "bits_per_key": 2,
   "k": 1,
   "queries": 5000000,
   "fpr_classic": 0.3934298,
   "fpr_blocked": 0.3936108,
   "fpr_register": 0.3931774,
   "fpr_textbook": 0.39346934,
   "fill_ratio": 0.393266
  },
  {
   "bits_per_key": 4,
   "k": 3,
   "queries": 5000000,
   "fpr_classic": 0.1471062,
   "fpr_blocked": 0.1480612,
   "fpr_register": 0.1562678,
   "fpr_textbook": 0.1468916,
   "fill_ratio": 0.52764
  },
  {
   "bits_per_key": 6,
   "k": 4,
   "queries": 5000000,
   "fpr_classic": 0.0560802,
   "fpr_blocked": 0.0581044,
   "fpr_register": 0.069337,
   "fpr_textbook": 0.056056671,
   "fill_ratio": 0.486536
  },
  {
   "bits_per_key": 8,
   "k": 6,
   "queries": 5000000,
   "fpr_classic": 0.0216034,
   "fpr_blocked": 0.0244002,
   "fpr_register": 0.037698,
   "fpr_textbook": 0.021577141,
   "fill_ratio": 0.527597
  },
  {
   "bits_per_key": 10,
   "k": 7,
   "queries": 5000000,
   "fpr_classic": 0.0082206,
   "fpr_blocked": 0.010462,
   "fpr_register": 0.0209968,
   "fpr_textbook": 0.0081937221,
   "fill_ratio": 0.503346
  },
  {
   "bits_per_key": 12,
   "k": 8,
   "queries": 5000000,
   "fpr_classic": 0.0031784,
   "fpr_blocked": 0.0047446,
   "fpr_register": 0.0128794,
   "fpr_textbook": 0.0031423503,
   "fill_ratio": 0.486528
  },
  {
   "bits_per_key": 14,
   "k": 10,
   "queries": 5000000,
   "fpr_classic": 0.0011556,
   "fpr_blocked": 0.002635,
   "fpr_register": 0.0099012,
   "fpr_textbook": 0.001201166,
   "fill_ratio": 0.510487
  },
  {
   "bits_per_key": 16,
   "k": 11,
   "queries": 6540069,
   "fpr_classic": 0.0004562643,
   "fpr_blocked": 0.0014866816,
   "fpr_register": 0.0070529837,
   "fpr_textbook": 0.00045871073,
   "fill_ratio": 0.49715
  },
  {
   "bits_per_key": 20,
   "k": 14,
   "queries": 44684694,
   "fpr_classic": 6.7674179e-05,
   "fpr_blocked": 0.00071241396,
   "fpr_register": 0.0049398123,
   "fpr_textbook": 6.7137081e-05,
   "fill_ratio": 0.503384
  },
  {
   "bits_per_key": 24,
   "k": 17,
   "queries": 304922130,
   "fpr_classic": 9.772987e-06,
   "fpr_blocked": 0.00047674139,
   "fpr_register": 0.0039856012,
   "fpr_textbook": 9.8385775e-06,
   "fill_ratio": 0.507519
  }
 ],
 "fpr_vs_k": [
  {
   "k": 1,
   "fpr": 0.0952065,
   "fpr_textbook": 0.095162582,
   "ns_per_negative_lookup": 2.632,
   "fill_ratio": 0.095148
  },
  {
   "k": 2,
   "fpr": 0.0328531,
   "fpr_textbook": 0.03285854,
   "ns_per_negative_lookup": 4.049,
   "fill_ratio": 0.181239
  },
  {
   "k": 3,
   "fpr": 0.01743785,
   "fpr_textbook": 0.017410586,
   "ns_per_negative_lookup": 5.604,
   "fill_ratio": 0.259145
  },
  {
   "k": 4,
   "fpr": 0.0118095,
   "fpr_textbook": 0.011813271,
   "ns_per_negative_lookup": 7.259,
   "fill_ratio": 0.329639
  },
  {
   "k": 5,
   "fpr": 0.00943765,
   "fpr_textbook": 0.0094309292,
   "ns_per_negative_lookup": 9.168,
   "fill_ratio": 0.393436
  },
  {
   "k": 6,
   "fpr": 0.008398,
   "fpr_textbook": 0.0084362093,
   "ns_per_negative_lookup": 11.31,
   "fill_ratio": 0.45117
  },
  {
   "k": 7,
   "fpr": 0.0082024,
   "fpr_textbook": 0.0081937221,
   "ns_per_negative_lookup": 13.05,
   "fill_ratio": 0.503346
  },
  {
   "k": 8,
   "fpr": 0.00848145,
   "fpr_textbook": 0.0084554723,
   "ns_per_negative_lookup": 14.222,
   "fill_ratio": 0.550617
  },
  {
   "k": 9,
   "fpr": 0.00914165,
   "fpr_textbook": 0.0091269931,
   "ns_per_negative_lookup": 15.871,
   "fill_ratio": 0.593412
  },
  {
   "k": 10,
   "fpr": 0.01014705,
   "fpr_textbook": 0.010185894,
   "ns_per_negative_lookup": 15.506,
   "fill_ratio": 0.632136
  },
  {
   "k": 11,
   "fpr": 0.01165505,
   "fpr_textbook": 0.011649504,
   "ns_per_negative_lookup": 15.982,
   "fill_ratio": 0.667083
  },
  {
   "k": 12,
   "fpr": 0.01353915,
   "fpr_textbook": 0.013560569,
   "ns_per_negative_lookup": 16.078,
   "fill_ratio": 0.698791
  },
  {
   "k": 13,
   "fpr": 0.015931,
   "fpr_textbook": 0.015980201,
   "ns_per_negative_lookup": 16.476,
   "fill_ratio": 0.727405
  },
  {
   "k": 14,
   "fpr": 0.01898075,
   "fpr_textbook": 0.018983799,
   "ns_per_negative_lookup": 16.991,
   "fill_ratio": 0.753331
  }
 ],
 "double_vs_independent": [
  {
   "bits_per_key": 6,
   "k": 4,
   "fpr_double": 0.0559934,
   "fpr_independent": 0.0561402,
   "ns_double": 11.833,
   "ns_independent": 13.613
  },
  {
   "bits_per_key": 8,
   "k": 6,
   "fpr_double": 0.0215578,
   "fpr_independent": 0.0215772,
   "ns_double": 13.464,
   "ns_independent": 15.512
  },
  {
   "bits_per_key": 10,
   "k": 7,
   "fpr_double": 0.0081618,
   "fpr_independent": 0.0081684,
   "ns_double": 13.183,
   "ns_independent": 15.29
  },
  {
   "bits_per_key": 12,
   "k": 8,
   "fpr_double": 0.0031208,
   "fpr_independent": 0.003161,
   "ns_double": 12.955,
   "ns_independent": 14.685
  },
  {
   "bits_per_key": 16,
   "k": 11,
   "fpr_double": 0.0004564172,
   "fpr_independent": 0.00045060687,
   "ns_double": 13.642,
   "ns_independent": 16.365
  }
 ],
 "small_filters": {
  "k": 7,
  "bits_per_key": 10,
  "trials": 300000,
  "probes_per_trial": 64,
  "rows": [
   {
    "m_bits": 128,
    "n": 12,
    "measured_independent": 0.0063870833,
    "measured_double": 0.0091072396,
    "textbook": 0.0059747881,
    "exact": 0.0064082535,
    "probes": 19200000
   },
   {
    "m_bits": 256,
    "n": 25,
    "measured_independent": 0.0075589062,
    "measured_double": 0.0089128125,
    "textbook": 0.0073024212,
    "exact": 0.0075597444,
    "probes": 19200000
   },
   {
    "m_bits": 512,
    "n": 51,
    "measured_independent": 0.0081778125,
    "measured_double": 0.0088885937,
    "textbook": 0.0080400547,
    "exact": 0.0081796627,
    "probes": 19200000
   },
   {
    "m_bits": 1024,
    "n": 102,
    "measured_independent": 0.0080853646,
    "measured_double": 0.0084616667,
    "textbook": 0.0080400547,
    "exact": 0.0081096792,
    "probes": 19200000
   },
   {
    "m_bits": 2048,
    "n": 204,
    "measured_independent": 0.0080514583,
    "measured_double": 0.0082861458,
    "textbook": 0.0080400547,
    "exact": 0.0080748221,
    "probes": 19200000
   },
   {
    "m_bits": 4096,
    "n": 409,
    "measured_independent": 0.0081710938,
    "measured_double": 0.0082292187,
    "textbook": 0.0081358537,
    "exact": 0.0081534125,
    "probes": 19200000
   }
  ]
 },
 "size_sweep": {
  "bits_per_key": 10,
  "k": 7,
  "queries_per_pass": 2000000,
  "rows": [
   {
    "n": 1000,
    "bytes": {
     "classic": 1256,
     "blocked": 1280,
     "register": 1256,
     "hashset": 32768
    },
    "neg_ns": {
     "classic": 10.144,
     "blocked": 10.092,
     "register": 3.386,
     "hashset": 10.209,
     "hash_only": 0.672
    },
    "pos_ns": {
     "classic": 3.377,
     "blocked": 3.673,
     "register": 3.369,
     "hashset": 5.188,
     "hash_only": 0.643
    },
    "insert_ns": {
     "classic": 3.0,
     "blocked": 4.0,
     "register": 3.0,
     "hashset": 1.0
    },
    "worst_over_best": 1.021
   },
   {
    "n": 10000,
    "bytes": {
     "classic": 12504,
     "blocked": 12544,
     "register": 12504,
     "hashset": 524288
    },
    "neg_ns": {
     "classic": 10.194,
     "blocked": 10.413,
     "register": 3.396,
     "hashset": 6.088,
     "hash_only": 0.676
    },
    "pos_ns": {
     "classic": 3.295,
     "blocked": 3.867,
     "register": 3.396,
     "hashset": 3.525,
     "hash_only": 0.625
    },
    "insert_ns": {
     "classic": 3.5,
     "blocked": 3.7,
     "register": 3.1,
     "hashset": 1.3
    },
    "worst_over_best": 1.025
   },
   {
    "n": 100000,
    "bytes": {
     "classic": 125000,
     "blocked": 125056,
     "register": 125000,
     "hashset": 4194304
    },
    "neg_ns": {
     "classic": 10.443,
     "blocked": 10.415,
     "register": 3.394,
     "hashset": 8.993,
     "hash_only": 0.684
    },
    "pos_ns": {
     "classic": 3.435,
     "blocked": 3.939,
     "register": 3.395,
     "hashset": 4.914,
     "hash_only": 0.642
    },
    "insert_ns": {
     "classic": 3.72,
     "blocked": 3.83,
     "register": 3.29,
     "hashset": 2.67
    },
    "worst_over_best": 1.028
   },
   {
    "n": 1000000,
    "bytes": {
     "classic": 1250000,
     "blocked": 1250048,
     "register": 1250000,
     "hashset": 33554432
    },
    "neg_ns": {
     "classic": 12.07,
     "blocked": 11.166,
     "register": 3.415,
     "hashset": 20.558,
     "hash_only": 0.67
    },
    "pos_ns": {
     "classic": 4.058,
     "blocked": 4.218,
     "register": 3.488,
     "hashset": 9.253,
     "hash_only": 0.637
    },
    "insert_ns": {
     "classic": 4.41,
     "blocked": 4.14,
     "register": 3.398,
     "hashset": 8.021
    },
    "worst_over_best": 1.026
   },
   {
    "n": 4000000,
    "bytes": {
     "classic": 5000000,
     "blocked": 5000000,
     "register": 5000000,
     "hashset": 134217728
    },
    "neg_ns": {
     "classic": 13.458,
     "blocked": 11.668,
     "register": 3.554,
     "hashset": 28.486,
     "hash_only": 0.674
    },
    "pos_ns": {
     "classic": 4.674,
     "blocked": 4.619,
     "register": 3.558,
     "hashset": 10.79,
     "hash_only": 0.623
    },
    "insert_ns": {
     "classic": 5.04,
     "blocked": 4.37,
     "register": 3.499,
     "hashset": 10.207
    },
    "worst_over_best": 1.02
   },
   {
    "n": 16000000,
    "bytes": {
     "classic": 20000000,
     "blocked": 20000000,
     "register": 20000000,
     "hashset": 536870912
    },
    "neg_ns": {
     "classic": 18.14,
     "blocked": 15.75,
     "register": 6.841,
     "hashset": 31.6,
     "hash_only": 0.679
    },
    "pos_ns": {
     "classic": 8.952,
     "blocked": 8.73,
     "register": 6.694,
     "hashset": 11.545,
     "hash_only": 0.634
    },
    "insert_ns": {
     "classic": 8.552,
     "blocked": 6.75,
     "register": 5.044,
     "hashset": 10.437
    },
    "worst_over_best": 1.184
   },
   {
    "n": 64000000,
    "bytes": {
     "classic": 80000000,
     "blocked": 80000000,
     "register": 80000000,
     "hashset": 2147483648
    },
    "neg_ns": {
     "classic": 25.551,
     "blocked": 16.83,
     "register": 11.011,
     "hashset": 34.637,
     "hash_only": 0.672
    },
    "pos_ns": {
     "classic": 20.239,
     "blocked": 14.942,
     "register": 11.031,
     "hashset": 11.76,
     "hash_only": 0.634
    },
    "insert_ns": {
     "classic": 23.496,
     "blocked": 15.387,
     "register": 11.641,
     "hashset": 11.335
    },
    "worst_over_best": 1.019
   }
  ]
 },
 "cache_sweep": {
  "n": 32000000,
  "bits_per_key": 10,
  "rows": [
   {
    "k": 1,
    "ns_classic": 5.139,
    "ns_blocked": 6.272
   },
   {
    "k": 2,
    "ns_classic": 7.001,
    "ns_blocked": 7.538
   },
   {
    "k": 3,
    "ns_classic": 8.956,
    "ns_blocked": 8.761
   },
   {
    "k": 4,
    "ns_classic": 10.797,
    "ns_blocked": 10.023
   },
   {
    "k": 5,
    "ns_classic": 12.631,
    "ns_blocked": 11.188
   },
   {
    "k": 6,
    "ns_classic": 14.693,
    "ns_blocked": 12.205
   },
   {
    "k": 7,
    "ns_classic": 16.644,
    "ns_blocked": 13.203
   },
   {
    "k": 8,
    "ns_classic": 18.63,
    "ns_blocked": 14.657
   },
   {
    "k": 9,
    "ns_classic": 20.34,
    "ns_blocked": 15.155
   },
   {
    "k": 10,
    "ns_classic": 22.094,
    "ns_blocked": 16.628
   },
   {
    "k": 11,
    "ns_classic": 24.167,
    "ns_blocked": 17.329
   },
   {
    "k": 12,
    "ns_classic": 26.027,
    "ns_blocked": 19.577
   }
  ]
 },
 "memory": {
  "n": 10000000,
  "rows": [
   {
    "what": "bloom filter",
    "detail": "8 bits/key, k=6",
    "bits_per_key": 8.0,
    "total_mb": 9.54,
    "fpr": 0.021577141,
    "exact": false
   },
   {
    "what": "bloom filter",
    "detail": "10 bits/key, k=7",
    "bits_per_key": 10.0,
    "total_mb": 11.92,
    "fpr": 0.0081937221,
    "exact": false
   },
   {
    "what": "bloom filter",
    "detail": "12 bits/key, k=8",
    "bits_per_key": 12.0,
    "total_mb": 14.31,
    "fpr": 0.0031423503,
    "exact": false
   },
   {
    "what": "bloom filter",
    "detail": "16 bits/key, k=11",
    "bits_per_key": 16.0,
    "total_mb": 19.07,
    "fpr": 0.00045871073,
    "exact": false
   },
   {
    "what": "bloom filter",
    "detail": "20 bits/key, k=14",
    "bits_per_key": 20.0,
    "total_mb": 23.84,
    "fpr": 6.7137081e-05,
    "exact": false
   },
   {
    "what": "the keys alone",
    "detail": "16 bytes each, zero overhead",
    "bits_per_key": 128.0,
    "total_mb": 152.59,
    "fpr": 0,
    "exact": true
   },
   {
    "what": "set of 64-bit fingerprints",
    "detail": "8 bytes each, zero overhead",
    "bits_per_key": 64.0,
    "total_mb": 76.29,
    "fpr": 5.4210109e-13,
    "exact": false
   },
   {
    "what": "open-addressed hash set",
    "detail": "16-byte keys, load 0.30",
    "bits_per_key": 429.5,
    "total_mb": 512.0,
    "fpr": 0,
    "exact": true
   }
  ]
 },
 "block_size_sweep": {
  "n": 16000000,
  "k": 7,
  "bits_per_key": 10,
  "cache_line_bytes": 128,
  "rows": [
   {
    "block_bits": 64,
    "block_bytes": 8,
    "fpr": 0.02620975,
    "neg_ns": 14.979,
    "pos_ns": 6.925
   },
   {
    "block_bits": 128,
    "block_bytes": 16,
    "fpr": 0.01707205,
    "neg_ns": 14.894,
    "pos_ns": 6.858
   },
   {
    "block_bits": 256,
    "block_bytes": 32,
    "fpr": 0.01260525,
    "neg_ns": 15.746,
    "pos_ns": 8.183
   },
   {
    "block_bits": 512,
    "block_bytes": 64,
    "fpr": 0.01039995,
    "neg_ns": 14.809,
    "pos_ns": 6.803
   },
   {
    "block_bits": 1024,
    "block_bytes": 128,
    "fpr": 0.009276,
    "neg_ns": 16.094,
    "pos_ns": 7.691
   },
   {
    "block_bits": 2048,
    "block_bytes": 256,
    "fpr": 0.00875345,
    "neg_ns": 16.031,
    "pos_ns": 7.151
   },
   {
    "block_bits": 4096,
    "block_bytes": 512,
    "fpr": 0.0085147,
    "neg_ns": 16.713,
    "pos_ns": 7.509
   }
  ]
 },
 "sink": 3684526981060899815
};
